apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  MONGODB_URI: mongodb://mongodb:27017/orders
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: makeline-service-config
data:
  MONGODB_URI: mongodb://mongodb:27017/makeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-service-config
data:
  USE_AZURE_OPENAI: "True"
  USE_AZURE_AD: "False"
  AZURE_OPENAI_API_VERSION: "2024-02-15-preview"
  AZURE_OPENAI_DEPLOYMENT_NAME: "gpt-4"
  AZURE_OPENAI_ENDPOINT: "https://akin0-m9m4xnhv-swedencentral.cognitiveservices.azure.com/"
  AZURE_OPENAI_DALLE_ENDPOINT: "https://akin0-m9m4xnhv-swedencentral.cognitiveservices.azure.com/"
  AZURE_OPENAI_DALLE_DEPLOYMENT_NAME: "dall-e-3"
