# apiVersion: v1
# kind: Secret
# metadata:
#   name: event-bus-and-ai-secrets
# type: Opaque
# data:
#   eventBusConnectionString: RW5kcG9pbnQ9c2I6Ly9teS1ldmVudGJ1cy04OTE1LnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9SExGM1ordTgrZk5BYnI1VEhOMGlSSjFQTGJ5MkdHT2JKK0FTYkNmY2VYST0=
#   openaiApiKey: QkZiOVpsY1k0d3JCdVFIRUJyVWZjWWdadVg4ckVjeXlzZzVnMXJUWTVaRnp3TmJTY0lIWkpRUUo5OUJEQUNmaE1rNVhKM3czQUFBQUFDT0c2ZUFO
apiVersion: v1
kind: Secret
metadata:
  name: azure-event-bus-secret
type: Opaque
data:
  connectionString: RW5kcG9pbnQ9c2I6Ly9teS1ldmVudGJ1cy04OTE1LnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9SExGM1ordTgrZk5BYnI1VEhOMGlSSjFQTGJ5MkdHT2JKK0FTYkNmY2VYST0=
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secret
type: Opaque
data:
  apiKey: QkZiOVpsY1k0d3JCdVFIRUJyVWZjWWdadVg4ckVjeXlzZzVnMXJUWTVaRnp3TmJTY0lIWkpRUUo5OUJEQUNmaE1rNVhKM3czQUFBQUFDT0c2ZUFO
